### ISSUE TITLE
Issues registering class which inherits an abstract class that doesn't need dependencies

### ISSUE THREAD

**Issue by ADRFranklin** [artberri/diod#16]
Hi, 

I am trying to register routes for an api, where each route is it's own class which inherits from a base class, however this base class is abstract and only requires a single variable being implemented which is an array of the methods that provide the routes to the router. The base class does not have any dependencies, but does require optional arguments to customise the router itself. 

The problem is that once diod see's multiple route classes being registered with the same base class, it expects the base class to be a service and even if you do make it as service, it  then complains at the arguments that are passed to it, since they are not dependencies, which is what it is expecting. 

How can I get it to ignore the base class since it's not special and isn't something to be injected? 

builder:
```ts
export default (builder: ContainerBuilder) => {
  [LegacyHealthRoutes, LegacyUserRoutes].forEach((route) => {
    builder
      .registerAndUse(route as any)
      .asSingleton()
      .addTag(HttpServerTags.HTTP_SERVER_LEGACY_ROUTE);
  });
};
```

Base Class
```ts
/**
 * Represents a base router that provides methods for defining routes and registering the router.
 */
export abstract class BaseRouter implements RouterProvider {
  /**
   * The router used for handling HTTP requests.
   */
  private router: ZodRouter;

  /**
   * Represents the routes of the base router.
   */
  protected abstract routes: Route[];

  /**
   * Represents the middleware providers for the base router.
   */
  private middleware: HttpKoaMiddlewareProvider[] = [];

  /**
   * Represents a base router for handling routes in a Koa HTTP server.
   */
  constructor(opts: {
    middleware?: HttpKoaMiddlewareProvider[];
    options?: RouterOpts;
  }) {
    this.router = zodRouter(opts.options);
    this.middleware = opts.middleware || [];
  }

  /**
   * Defines a route using the provided router specification.
   * @param routerSpec - The router specification used to create the route.
   */
  public defineRoute = routerSpec.createRouteSpec;

  /**
   * Registers the router by creating a new instance of the Router class.
   * @returns The registered router instance.
   */
  async register() {
    this.middleware.forEach(async (middleware) => {
      this.router.use(await middleware.register());
    });
    this.routes.forEach((route) => {
      this.router.register(route);
    });

    return this.router;
  }

  /**
   * Checks if the given router is an instance of BaseRouter.
   * @param router - The router to check.
   * @returns True if the router is an instance of BaseRouter, false otherwise.
   */
  static isBaseRouterProvider(router: unknown): router is RouterProvider {
    return router instanceof BaseRouter;
  }
}
```

Example route class that extends the base class
```ts
@Service()
/**
 * Represents the legacy health routes.
 */
export class LegacyHealthRoutes extends BaseRouter {
  /**
   * Represents the Health class.
   * @constructor
   */
  constructor() {
    super({
      options: {
        koaRouter: {
          prefix: '/health',
        },
      },
    });
  }

  /**
   * Retrieves the health status.
   *
   * @returns {Promise<void>} A promise that resolves when the health status is retrieved.
   */
  private getHealth = this.defineRoute({
    name: 'GetHealth',
    method: 'get',
    path: '/',
    handler: async (ctx, next) => {
      ctx.status = 200;
      ctx.body = {
        status: 'ok',
      };
    },
  });

  /**
   * Represents the routes for the health endpoint.
   */
  protected routes: Route[] = [this.getHealth];
}
```

Error before making base class a service
```
[2024-06-30 08:51:22.672 +0000] ERROR: something unexpected went wrong 
    err: {
      "type": "Error",
      "message": "Service not decorated: LegacyHealthRoutes -> BaseRouter",
      "stack":
          Error: Service not decorated: LegacyHealthRoutes -> BaseRouter
              at getDependenciesFromDecoratedServiceOrThrow (/workspace/node_modules/diod/lib/diod.js:91:11)
              at getDependencies (/workspace/node_modules/diod/lib/diod.js:105:24)
              at getDependencies (/workspace/node_modules/diod/lib/diod.js:114:12)
              at ClassConfiguration.setDependencyInformationIfNotExist (/workspace/node_modules/diod/lib/diod.js:190:27)
              at ClassConfiguration.build (/workspace/node_modules/diod/lib/diod.js:194:10)
              at Object.build (/workspace/node_modules/diod/lib/diod.js:209:31)
              at DiodRegistration.build (/workspace/node_modules/diod/lib/diod.js:301:27)
              at Object.build (/workspace/node_modules/diod/lib/diod.js:307:40)
              at ContainerBuilder.build (/workspace/node_modules/diod/lib/diod.js:386:30)
              at _default (/workspace/server/src/builder.ts:15:27)
              at /workspace/server/src/app.ts:107:25
              at Object.<anonymous> (/workspace/server/src/app.ts:119:1)
              at Module._compile (node:internal/modules/cjs/loader:1376:14)
              at Module.m._compile (/workspace/node_modules/ts-node/src/index.ts:1618:23)
              at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
              at Object.require.extensions.<computed> [as .ts] (/workspace/node_modules/ts-node/src/index.ts:1621:12)
    }
```

Error after making the base class a service
```
[2024-06-30 09:01:44.016 +0000] ERROR: something unexpected went wrong 
    err: {
      "type": "Error",
      "message": "Service not registered for the following dependencies of LegacyHealthRoutes: Object",
      "stack":
          Error: Service not registered for the following dependencies of LegacyHealthRoutes: Object
              at verifyMetadata (/workspace/node_modules/diod/lib/diod.js:320:11)
              at verifyAllServices (/workspace/node_modules/diod/lib/diod.js:349:5)
              at verify (/workspace/node_modules/diod/lib/diod.js:353:3)
              at ContainerBuilder.build (/workspace/node_modules/diod/lib/diod.js:389:5)
              at _default (/workspace/server/src/builder.ts:15:27)
              at /workspace/server/src/app.ts:107:25
              at Object.<anonymous> (/workspace/server/src/app.ts:119:1)
              at Module._compile (node:internal/modules/cjs/loader:1376:14)
              at Module.m._compile (/workspace/node_modules/ts-node/src/index.ts:1618:23)
              at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
              at Object.require.extensions.<computed> [as .ts] (/workspace/node_modules/ts-node/src/index.ts:1621:12)
              at Module.load (node:internal/modules/cjs/loader:1207:32)
              at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
              at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
              at phase4 (/workspace/node_modules/ts-node/src/bin.ts:649:14)
              at bootstrap (/workspace/node_modules/ts-node/src/bin.ts:95:10)
    }
```

**Comment by artberri** [comment]
Hi @ADRFranklin 

Thank you very much for reporting and sorry for the late response. This is a good catch, derived classes with parameterless constructor were still asking to register their base class which is incorrect. As you said, the base class should be ignored in this case.

I've fixed the issue in [this commit](https://github.com/artberri/diod/commit/2a29a37ef2da9779ed4d7e790c87d47addb13312) and the fix will be available in the new version that will be released soon (v3.0.0).

The fix is a bit hacky, but I didn't find a better way to detect that the derived class is declaring an empty constructor by itself. Anyway, I think it will work.

Thank you again.
